/*
Copyright (C) 2013-2016, The Regents of The University of Michigan.
All rights reserved.
This software was developed in the APRIL Robotics Lab under the
direction of Edwin Olson, ebolson@umich.edu. This software may be
available under alternative licensing terms; contact the address above.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
The views and conclusions contained in the software and documentation are those
of the authors and should not be interpreted as representing official policies,
either expressed or implied, of the Regents of The University of Michigan.
*/

#pragma once

#include <cstdint>

#include "zarray.h"


namespace apriltag
{
	struct quad_t
	{
		float p[4][2]; // corners

		bool reversed_border;

		// H: tag coordinates ([-1,1] at the black corners) to pixels
		// Hinv: pixels to tag
		// matd_t *H, *Hinv;
		double h[9];
	};

	quad_t* quad_copy(const quad_t* quad)
	{
		quad_t* q = (quad_t*)calloc(1, sizeof(quad_t));
		memcpy(q, quad, sizeof(quad_t));
		return q;
	}

	void quad_destroy(quad_t* quad)
	{
		if (!quad)
			return;
		free(quad);
	}

	// Represents a tag family. Every tag belongs to a tag family. Tag
	// families are generated by the Java tool
	// april.tag.TagFamilyGenerator and can be converted to C using
	// april.tag.TagToC.
	struct apriltag_family_t
	{
		// How many codes are there in this tag family?
		uint32_t ncodes;

		// The codes in the family.
		uint64_t* codes = nullptr;

		int width_at_border;
		int total_width;
		bool reversed_border;

		// The bit locations.
		uint32_t nbits;
		uint32_t* bit_x = nullptr;
		uint32_t* bit_y = nullptr;

		// minimum hamming distance between any two codes. (e.g. 36h11 => 11)
		uint32_t h;

		// a human-readable name, e.g., "tag36h11"
		// char* name = nullptr;

		// some detector implementations may preprocess codes in order to
		// accelerate decoding.  They put their data here. (Do not use the
		// same apriltag_family instance in more than one implementation)
		void* impl = nullptr;
	};

	void tag_destroy(apriltag_family_t* tf)
	{
		// if (tf->codes)
		// 	free(tf->codes);
		if (tf->bit_x)
			free(tf->bit_x);
		if (tf->bit_y)
			free(tf->bit_y);
		// if (tf->name)
		// 	free(tf->name);
		free(tf);
	}

	// Represents a detector object. Upon creating a detector, all fields
	// are set to reasonable values, but can be overridden by accessing
	// these fields.
	struct apriltag_detector_t
	{
		///////////////////////////////////////////////////////////////
		// User-configurable parameters.

		// detection of quads can be done on a lower-resolution image,
		// improving speed at a cost of pose accuracy and a slight
		// decrease in detection rate. Decoding the binary payload is
		// still done at full resolution. .
		float quad_decimate;

		// What Gaussian blur should be applied to the segmented image
		// (used for quad detection?)  Parameter is the standard deviation
		// in pixels.  Very noisy images benefit from non-zero values
		// (e.g. 0.8).
		float quad_sigma;

		// When non-zero, the edges of the each quad are adjusted to "snap
		// to" strong gradients nearby. This is useful when decimation is
		// employed, as it can increase the quality of the initial quad
		// estimate substantially. Generally recommended to be on (1).
		//
		// Very computationally inexpensive. Option is ignored if
		// quad_decimate = 1.
		int refine_edges;

		// How much sharpening should be done to decoded images? This
		// can help decode small tags but may or may not help in odd
		// lighting conditions or low light conditions.
		//
		// The default value is 0.25.
		double decode_sharpening;

		// reject quads containing too few pixels
		int min_cluster_pixels;

		// reject quads containing too many pixels
		int max_cluster_pixels;

		// how many corner candidates to consider when segmenting a group
		// of pixels into a quad.
		int max_nmaxima;

		// Reject quads where pairs of edges have angles that are close to
		// straight or close to 180 degrees. Zero means that no quads are
		// rejected. (In radians).
		// fix - not use.
		//float critical_rad;
		double cos_critical_rad;

		// When fitting lines to the contours, what is the maximum mean
		// squared error allowed?  This is useful in rejecting contours
		// that are far from being quad shaped; rejecting these quads "early"
		// saves expensive decoding processing.
		double max_line_fit_mse;

		// When we build our model of black & white pixels, we add an
		// extra check that the white model must be (overall) brighter
		// than the black model.  How much brighter? (in pixel values,
		// [0,255]). .
		int min_white_black_diff;

		// should the thresholded image be deglitched? Only useful for
		// very noisy images
		int deglitch;

		// minimum area of tag
		int min_tag_area;

		///////////////////////////////////////////////////////////////
		// Statistics relating to last processed frame
		//timeprofile_t* tp;

		uint32_t nedges;
		uint32_t nsegments;
		uint32_t nquads;

		///////////////////////////////////////////////////////////////
		// Internal variables below

		// Not freed on apriltag_destroy; a tag family can be shared
		// between multiple users. The user should ultimately destroy the
		// tag family passed into the constructor.
		zarray_t* tag_families;
	};

	// Represents the detection of a tag. These are returned to the user
	// and must be individually destroyed by the user.
	struct apriltag_detection_t
	{
		// a pointer for convenience. not freed by apriltag_detection_destroy.
		apriltag_family_t* family;

		// The decoded ID of the tag
		int id;

		// How many error bits were corrected? Note: accepting large numbers of
		// corrected errors leads to greatly increased false positive rates.
		// NOTE: As of this implementation, the detector cannot detect tags with
		// a hamming distance greater than 2.
		int hamming;

		// A measure of the quality of the binary decoding process: the
		// average difference between the intensity of a data bit versus
		// the decision threshold. Higher numbers roughly indicate better
		// decodes. This is a reasonable measure of detection accuracy
		// only for very small tags-- not effective for larger tags (where
		// we could have sampled anywhere within a bit cell and still
		// gotten a good detection.)
		float decision_margin;

		// The 3x3 homography matrix describing the projection from an
		// "ideal" tag (with corners at (-1,1), (1,1), (1,-1), and (-1,
		// -1)) to pixels in the image. This matrix will be freed by
		// apriltag_detection_destroy.
		// matd_t* H;
		double h[9];

		// The center of the detection in image pixel coordinates.
		double c[2];

		// The corners of the tag in image pixel coordinates. These always
		// wrap counter-clock wise around the tag.
		double p[4][2];
	};

	// Call this method on each of the tags returned by apriltag_detector_detect
	void apriltag_detection_destroy(apriltag_detection_t* det)
	{
		if (det == NULL)
			return;
		free(det);
	}

	// destroys the array AND the detections within it.
	void apriltag_detections_destroy(zarray_t* detections)
	{
		for (int i = 0; i < zarray_size(detections); i++) {
			apriltag_detection_t* det;
			zarray_get(detections, i, &det);
			apriltag_detection_destroy(det);
		}
		zarray_destroy(detections);
	}

	struct quick_decode_entry_t
	{
		uint64_t rcode;   // the queried code
		uint16_t id;      // the tag ID (a small integer)
		uint8_t hamming;  // how many errors corrected?
		uint8_t rotation; // number of rotations [0, 3]
	};

	struct quick_decode_t
	{
		int nentries;
		quick_decode_entry_t* entries;
	};

	// Regresses a model of the form:
	// intensity(x,y) = C0*x + C1*y + CC2
	// The J matrix is the:
	//    J = [ x1 y1 1 ]
	//        [ x2 y2 1 ]
	//        [ ...     ]
	//  The A matrix is J'J
	struct graymodel_t
	{
		double A[3][3];
		double B[3];
		double C[3];
	};
}